name: Check PR
on: [push]

jobs:
  build:
    name: Check PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: lokkju/github-action-sbt@master
        with:
          commands: checkPR
